#define LWIP_CHARGEN_APP              0
#define LWIP_DNS_APP                  0
#define LWIP_HTTPD_APP                0
/*#define LWIP_HTTPD_APP_NETCONN     */
#define LWIP_NETBIOS_APP              0
#define LWIP_NETIO_APP                0
#define LWIP_MDNS_APP                 0
#define LWIP_MQTT_APP                 0
#define LWIP_PING_APP                 0
#define LWIP_RTP_APP                  0
#define LWIP_SHELL_APP                0
#define LWIP_SNMP_APP                 0
#define LWIP_SNTP_APP                 0
#define LWIP_SOCKET_EXAMPLES_APP      0
#define LWIP_TCPECHO_APP              0
/*#define LWIP_TCPECHO_APP_NETCONN   */
#define LWIP_TFTP_APP                 0
#define LWIP_UDPECHO_APP              0
#define LWIP_LWIPERF_APP              0

#define USE_DHCP    1
#define USE_AUTOIP  0
